input_features:
    -
        name: image_path
        type: image
        encoder: resnet
        preprocessing:
          height: 256
          width: 256
          resize_method: interpolate
          num_channels: 3
          in_memory: false

output_features:
    -
        name: caption
        type: text
        level: word
        decoder: generator
        cell_type: lstm

training:
    batch_size: 1